packages:
  - 'demo'
  - 'packages/*'

allowBuilds:
  '0': '@reown/appkit'
  '1': bufferutil
  '2': keccak
  '3': msgpackr-extract
  '4': sharp
  '5': unrs-resolver
  '6': utf-8-validate
  '@reown/appkit': true
  bufferutil: true
  keccak: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
